version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_DB=htmlcourse_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: